---
title: "2-wsoc"
author: "Kaizad F. Patel"
date: "October 2019"
output: html_document
---

This script reads WSOC data files for (a) soil extracts and (b) pore water samples, 
creates summary tables and graphs.

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("0-packages.R")
```

# WSOC concentrations -- pores

```{r data-prep, include=FALSE}
wsoc_pores = read_excel("data/3Soils_WSOC_CN_PoreCore.xlsx")
names(wsoc_pores)

wsoc_pores$wsoc = wsoc_pores$`Water Soluble Organic Carbon (mg/L)`

#rename and reorder factors in Treatment 
wsoc_pores$Treatment = factor(wsoc_pores$Treatment,
                              levels = c("Time Zero Saturation",
                                         "Field Moisture Incubation",
                                         "Saturation Incubation",
                                         "Drought Incubation"),
                              labels = c("Time Zero",
                                         "Field Moist",
                                         "Saturated",
                                         "Drought"))

## making separate plots for sites 
#creating summary
wsoc_pores %>% 
  group_by(Site, Suction, Treatment) %>% 
  dplyr::summarise(N = n(), sd = sd(wsoc, na.rm = TRUE), wsoc = mean(wsoc, na.rm = TRUE)) ->
  wsoc_rmisc

wsoc_cpcrw <- wsoc_pores[wsoc_pores$Site == "CPCRW",]
wsoc_dwp <- wsoc_pores[wsoc_pores$Site == "DWP",]
wsoc_sr <- wsoc_pores[wsoc_pores$Site == "SR",]
```

```{r plot-functions}
theme_kp <- function() {  # this for all the elements common across plots
  theme_bw() %+replace%
    theme(legend.position = "none",
          legend.key = element_rect(size = 3),
          legend.title = element_blank(),
          legend.text = element_text(size = 12),
          legend.key.size = unit(1.5, 'lines'),
          plot.title = element_text(hjust = 0.05, size = 14),
          axis.text = element_text(size = 14, face = "bold", color = "black"),
          axis.title = element_text(size = 14, face = "bold", color = "black"))
}

base_plot <- function(summary_dat, base_dat) {
  ggplot(summary_dat, 
         aes(x = Treatment, y = wsoc,color = Suction, fill = Suction)) +
    geom_bar(stat = "summary", width = 0.5, 
             position = position_dodge(0.6), color = "black", size = 1) +
    geom_errorbar(aes(ymin = wsoc - sd, ymax = wsoc + sd), 
                  width = 0.2, position = position_dodge(0.6), color = "black", size = 1) +
    geom_point(data = base_dat, aes(x = Treatment, y = wsoc), 
               color = "black", position = position_dodge(0.6), na.rm = TRUE) +
    
    xlab("") +
    ylab(expression(bold("WSOC, mg L"^-1))) +
    ylim(0, 350) +
    theme_kp()
}
```

## CPCRW

```{r plot1}
gg_wsoc_pores_cpcrw <- base_plot(filter(wsoc_rmisc, Site == "CPCRW"), wsoc_cpcrw) +
  annotate("text", label = "B", x = 0.85, y = 70, size = 4, fontface = "bold") + 
  annotate("text", label = "B", x = 1.15, y = 70, size = 4, fontface = "bold") + 
  annotate("text", label = "B", x = 1.85, y = 80, size = 4, fontface = "bold") + 
  annotate("text", label = "B", x = 2.15, y = 80, size = 4, fontface = "bold") + 
  annotate("text", label = "B", x = 2.85, y = 120, size = 4, fontface = "bold") + 
  annotate("text", label = "AB", x = 3.15, y = 180, size = 4, fontface = "bold") + 
  annotate("text", label = "AB", x = 3.85, y = 300, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 4.15, y = 345, size = 4, fontface = "bold") + 
  
  theme(legend.position = c(0.2, 0.8),
        legend.key = element_rect(size = 2),
        legend.key.size = unit(2, 'lines')) +
  ggtitle("CPCRW")

print(gg_wsoc_pores_cpcrw)
save_plot("output/wsoc_cpcrw.tiff", gg_wsoc_pores_cpcrw, base_height = 10, base_width = 10)
```

## DWP

```{r plot2}
gg_wsoc_pores_dwp <- base_plot(filter(wsoc_rmisc, Site == "DWP"), wsoc_dwp) + 
  annotate("text", label = "A", x = 0.85, y = 170, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 1.15, y = 170, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 1.85, y = 100, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 2.15, y = 100, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 2.85, y = 80, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 3.15, y = 170, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 3.85, y = 150, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 4.15, y = 150, size = 4, fontface = "bold") + 
  
  theme (legend.position = "none",
         legend.key = element_rect(size = 2),
         legend.key.size = unit(2, 'lines')) +
  ggtitle ("DWP")

print(gg_wsoc_pores_dwp)
save_plot("wsoc_dwp.tiff", gg_wsoc_pores_dwp, base_height = 10, base_width = 10)
```

## Secret River

```{r plot3}
gg_wsoc_pores_sr <- base_plot(filter(wsoc_rmisc, Site == "SR"), wsoc_sr) +
  annotate("text", label = "B", x = 0.85, y = 20, size = 4, fontface = "bold") + 
  annotate("text", label = "B", x = 1.15, y = 20, size = 4, fontface = "bold") + 
  annotate("text", label = "AB", x = 1.85, y = 50, size = 4, fontface = "bold") + 
  annotate("text", label = "AB", x = 2.15, y = 50, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 2.85, y = 50, size = 4, fontface = "bold") + 
  annotate("text", label = "A", x = 3.15, y = 50, size = 4, fontface = "bold") + 
  annotate("text", label = "AB", x = 3.85, y = 50, size = 4, fontface = "bold") + 
  annotate("text", label = "AB", x = 4.15, y = 50, size = 4, fontface = "bold") + 
  
  theme(legend.position = "none",
        legend.key = element_rect(size = 1),
        legend.key.size = unit(1.5, 'lines')) +
  ggtitle("SR")

print(gg_wsoc_pores_sr)
save_plot("wsoc_sr.tiff", gg_wsoc_pores_sr,base_height = 10, base_width = 10)

porewater <- plot_grid(gg_wsoc_pores_cpcrw, gg_wsoc_pores_dwp, gg_wsoc_pores_sr, 
                       nrow = 2, ncol = 2, align = "hv", axis = "bt")
print(porewater)
save_plot("output/wsoc_pores.tiff", porewater, base_width = 12, base_height = 12)

plot_grid(gg_wsoc_pores_cpcrw, gg_wsoc_pores_dwp, gg_wsoc_pores_sr,
          ncol = 2, nrow = 2, align = "hv")
```

## Summary table

```{r summary-table}
wsoc_rmisc %>% 
  ungroup %>% 
  mutate(sp = paste(Site, Suction), 
         val = paste(round(wsoc, 1), "\u00B1", round(sd, 1))) %>% 
  select(Treatment, sp, val) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")
```

