---
title: "6-fticr_pores_output"
author: "Kaizad Patel"
date: "10/10/2019"
output: bookdown::html_document2
---


```{r setup, include=FALSE, echo=FALSE}
source("0-packages.R")

#input files
pore_aromatic = read.csv(FTICR_PORE_AROMATIC)# <- "fticr/fticr_pore_aromatic_counts.csv"
pore_meta = read.csv(FTICR_PORE_META)# <- "fticr/fticr_pore_meta.csv"
pore_long = read.csv(FTICR_PORE_LONG)# <- "fticr/fticr_pore_longform.csv"
pore_relabund = read.csv(FTICR_PORE_RELABUND)# <- "fticr/fticr_pore_relabundance_groups2_hsd.csv"
pore_peaks = read.csv(FTICR_PORE_PEAKS)# <- "fticr/fticr_pore_peakscount.csv"
pore_unique = read.csv(FTICR_PORE_UNIQUE)# <- "fticr/fticr_pore_uniquemolecules.csv"
pore_unique_peaks = read.csv(FTICR_PORE_UNIQUE_PEAKS)# <- "fticr/fticr_pore_unique_peakscount.csv"
pore_hcoc = read.csv(FTICR_PORE_HCOC)# <- "fticr/fticr_pore_hcoc.csv"
pore_nosc = read.csv(FTICR_PORE_NOSC)# <- "fticr/fticr_pore_nosc.csv"
```


# Pores -- figures
## aromatic peaks
```{r aromatic, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="aromatic peaks", fig.width=12, fig.height=7}
pore_aromatic %>% 
  mutate(treatment = factor(treatment,
                            levels = c("baseline","time zero saturation", "field moist","saturation","drought")))->
  pore_aromatic

## doing facet
ggplot(pore_aromatic, 
  aes(x = site, y = arom_core_counts, color = treatment, fill = treatment))+
  geom_boxplot(position = "dodge", fill = "white", lwd = 1,fatten = 1)+ # fatten changes thickness of median line, lwd changes thickness of all lines
  geom_dotplot(binaxis = "y",position = position_dodge(0.75), 
               stackdir = "center", dotsize = 0.4, color = "black")+
  
  #scale_fill_viridis_d(option = "magma")+
  #scale_color_viridis_d(option = "magma")+

  scale_fill_brewer(palette = "Dark2")+
  scale_color_brewer(palette = "Dark2")+

  ylab("aromatic peaks")+
  xlab("")+
  ylim(0,350)+
  geom_vline(xintercept = 1.5)+
  geom_vline(xintercept = 2.5)+
  
  facet_wrap(~tension)+
  
  theme_bw()+
  theme_kp()

```

## native SOM
```{r vk_baseline, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="Van Krevelen plot for TZSat pores",fig.width=10, fig.height=7}

ggplot(pore_hcoc[pore_hcoc$treatment=="time zero saturation",],
       aes(x = OC, y = HC, color = site))+
  geom_point(alpha = 0.1)+
  scale_color_brewer(palette = "Set1")+
  
  xlab("O/C")+
  ylab("H/C")+
  xlim(0,1.27)+
  ylim(0,2.7)+
  
  geom_segment(x = 0.0, y = 1.5, xend = 1.2, yend = 1.5,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 2, xend = 1.2, yend = 2,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 1, xend = 1.2, yend = 0.75,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 0.7, xend = 1.2, yend = 0.5,color="black",linetype="longdash")+

  facet_grid(tension~site)+
  
  guides(colour = guide_legend(override.aes = list(alpha = 1)))+
  theme_bw()+
  theme_kp()
```

## treatment effect
```{r vk_treatments, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="Van Krevelen plot for treatments",fig.width=10, fig.height=7}
pore_hcoc %>% 
  mutate(treatment = factor(treatment, levels = c("time zero saturation","field moist","drought","saturation")))->
           pore_hcoc2

ggplot(pore_hcoc2[!pore_hcoc2$treatment=="time zero saturation",], # remove baseline 
         aes(x = OC, y = HC, color = treatment))+
  geom_point(alpha = 0.1)+
  scale_color_brewer(palette = "Dark2")+
  
  geom_segment(x = 0.0, y = 1.5, xend = 1.2, yend = 1.5,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 2, xend = 1.2, yend = 2,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 1, xend = 1.2, yend = 0.75,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 0.7, xend = 1.2, yend = 0.5,color="black",linetype="longdash")+

  xlab("O/C")+
  ylab("H/C")+
  xlim(0,1.27)+
  ylim(0,2.7)+
  
  geom_segment(x = 0.0, y = 1.5, xend = 1.2, yend = 1.5,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 2, xend = 1.2, yend = 2,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 1, xend = 1.2, yend = 0.75,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 0.7, xend = 1.2, yend = 0.5,color="black",linetype="longdash")+

  facet_grid(tension~site)+
  
  guides(colour = guide_legend(override.aes = list(alpha = 1)))+
  theme_bw()+
  theme_kp()

```

## treatment effect -- unique molecules
```{r vk_unique, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="Van Krevelen plot for uniqiue peaks",fig.width=10, fig.height=7}
# set level of factors
pore_unique %>% 
  mutate(unique = factor(unique, levels = c("field_moist","drought","saturation")))->
           pore_unique

ggplot(pore_unique,
         aes(x = OC, y = HC, color = unique))+
  geom_point(alpha = 0.4)+
  scale_color_brewer(palette = "Dark2")+

  xlab("O/C")+
  ylab("H/C")+
  xlim(0,1.27)+
  ylim(0,2.7)+
  
  geom_segment(x = 0.0, y = 1.5, xend = 1.2, yend = 1.5,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 2, xend = 1.2, yend = 2,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 1, xend = 1.2, yend = 0.75,color="black",linetype="longdash")+
  geom_segment(x = 0.0, y = 0.7, xend = 1.2, yend = 0.5,color="black",linetype="longdash")+

  facet_grid(tension~site)+
  
  guides(colour = guide_legend(override.aes = list(alpha = 1)))+
  theme_bw()+
  theme_kp()

```

## treatment effect -- relative abundance
```{r rel_abund, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="Relative abundance",fig.width=9, fig.height=9}
# use file fticr_pore_relabundance_summary
# first, remove the `total` row
pore_relabund = pore_relabund[!pore_relabund$group=="total",]

# set Other as last factor
old.lvl = levels(factor(pore_relabund$group))
pore_relabund$group = factor(pore_relabund$group, 
                                            levels=c(sort(old.lvl[old.lvl!="Other"]), "Other"))

ggplot(pore_relabund, aes(x = treatment, y = relabund, fill = group))+
  geom_bar(stat = "summary", width = 0.9)+
  #scale_fill_brewer(palette = "Dark2")+
  scale_fill_viridis_d(option = "inferno")+
  
  xlab("")+
  ylab("% relative abundance")+
  
  facet_grid(tension~site)+
  
  theme_bw()+
  theme_kp()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## treatment effect -- NOSC
```{r NOSC_c, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="NOSC for CPCRW",fig.width=11, fig.height=6}
pore_nosc %>% 
  mutate(treatment = factor(treatment,
                            levels = c("baseline","time zero saturation", "field moist","drought","saturation")))->
  pore_nosc

#CPCRW
ggplot(pore_nosc[pore_nosc$site=="CPCRW" &!pore_nosc$treatment=="baseline",], 
       aes(x = NOSC, fill = treatment, color = treatment))+
  geom_histogram(binwidth = 0.25, position = "identity", alpha = 0.2)+
  #scale_fill_brewer(palette = "Dark2")+
  scale_color_brewer(palette = "Dark2")+
  scale_fill_manual(values = c("#666666","#1B9E77", "#D95F02", "#7570B3"))+
  scale_color_manual(values = c("#666666","#1B9E77", "#D95F02", "#7570B3"))+
  #geom_histogram(data = subset(fticr_pore_nosc, site = "CPCRW" | treatment=="field moist"), fill = "red", alpha = 0.2)+

  xlim(-2.5, 2.5)+
  ylim(0,3000)+
  ggtitle("CPCRW")+
  
  facet_grid(tension~treatment)+ #facet with two variables
  
  theme_bw()+
  theme_kp()
```

```{r NOSC_d, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="NOSC for DWP",fig.width=11, fig.height=6}
#DWP
ggplot(pore_nosc[pore_nosc$site=="DWP" &!pore_nosc$treatment=="baseline",], 
       aes(x = NOSC, fill = treatment, color = treatment))+
  geom_histogram(binwidth = 0.25, position = "identity", alpha = 0.2)+
  #scale_fill_brewer(palette = "Dark2")+
  scale_color_brewer(palette = "Dark2")+
  scale_fill_manual(values = c("#666666","#1B9E77", "#D95F02", "#7570B3"))+
  scale_color_manual(values = c("#666666","#1B9E77", "#D95F02", "#7570B3"))+
  #geom_histogram(data = subset(fticr_pore_nosc, site = "CPCRW" | treatment=="field moist"), fill = "red", alpha = 0.2)+

  xlim(-2.5, 2.5)+
  ylim(0,3000)+
  ggtitle("DWP")+
  
  facet_grid(tension~treatment)+ #facet with two variables
  
  theme_bw()+
  theme_kp()
```

```{r NOSC_s, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="NOSC for SR",fig.width=11, fig.height=6}

#SR
ggplot(pore_nosc[pore_nosc$site=="SR" &!pore_nosc$treatment=="baseline",], 
       aes(x = NOSC, fill = treatment, color = treatment))+
  geom_histogram(binwidth = 0.25, position = "identity", alpha = 0.2)+
  #scale_fill_brewer(palette = "Dark2")+
  scale_color_brewer(palette = "Dark2")+
  scale_fill_manual(values = c("#666666","#1B9E77", "#D95F02", "#7570B3"))+
  scale_color_manual(values = c("#666666","#1B9E77", "#D95F02", "#7570B3"))+
  #geom_histogram(data = subset(fticr_pore_nosc, site = "CPCRW" | treatment=="field moist"), fill = "red", alpha = 0.2)+

  xlim(-2.5, 2.5)+
  ylim(0,3000)+
  ggtitle("SR")+
  
  facet_grid(tension~treatment)+ #facet with two variables
  
  theme_bw()+
  theme_kp()
```


# Pores -- tables
## peaks
```{r peaks, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="peaks 50 kPa", }
pore_peaks %>% 
  ungroup %>% 
    filter(tension=="50 kPa") %>% 
dplyr::mutate(sp = paste(site, treatment),
                val = paste(peaks_count)) %>% 
  select(Class,sp, val) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")
```

```{r peaks_1, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="peaks 1.5 kPa"}
pore_peaks %>% 
  ungroup %>% 
  filter(tension=="1.5 kPa") %>% 
  dplyr::mutate(sp = paste(site, treatment),
                val = paste(peaks_count)) %>% 
  select(Class,sp, val) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")
```

## relative abundance

```{r relabund_50, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="relabund 50 kPa"}
pore_relabund%>% 
  ungroup %>% 
  filter(tension=="50 kPa") %>% 
  dplyr::mutate(sp = paste(site, treatment),
                val = paste(relativeabundance)) %>% 
  select(group,sp, val) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")
```
total = 100%

```{r relabund_5, echo=FALSE, warning=FALSE,message=FALSE,fig.cap="relabund 1.5 kPa"}
pore_relabund%>% 
  ungroup %>% 
  filter(tension=="1.5 kPa") %>% 
  dplyr::mutate(sp = paste(site, treatment),
                val = paste(relativeabundance)) %>% 
  select(group,sp, val) %>% 
  spread(sp, val) %>% 
  knitr::kable(align = "r")
```
total = 100%

