---
title: "5b-fluxes_graphs"
author: "Kaizad Patel"
date: "1/20/2020"
output: word_document
---

```{r,echo=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      fig.path = "images/markdown-flux/")
```

```{r}
source("0-functions.R")
source("0b-packages.R")

flux_temp = read_csv("processed/fluxdata_kp.csv")

```

```{r}
# remove pre-incubation data
flux = 
  flux_temp %>% 
#  filter(!TREATMENT_PHASE == "DROUGHT_PRE_INCUBATION") %>% 
#  filter(!TREATMENT_PHASE == "DROUGHT4C_PRE_INCUBATION") %>% 
  filter(!SampleID=="S5")  %>% 
  filter(!Treatment=="sat_I") %>% 
# rename the incubation and saturation phases  
  dplyr::mutate(TREATMENT_PHASE = case_when(grepl("_INCUBATION",TREATMENT_PHASE)~"incubation",
                                            grepl("_SATURATION",TREATMENT_PHASE)~"post-incub saturation"),
                Treatment = case_when(Treatment=="field_moist"~ "field moist",
                                      Treatment=="sat_II" ~ "flood",
                                      Treatment=="drought" ~ "drought"),
                Site = case_when(Site=="CPCRW" ~ "Alaska",
                                 Site=="DWP" ~ "Florida",
                                 Site=="SR" ~ "Washington")) %>% 
  filter(!(Treatment=="flood"&TREATMENT_PHASE=="post-incub saturation"))
```

```{r, fig.width=8, fig.height=8}
ggplot(flux, aes(x = time_hours, y = CO2_mgC_gSoil_hr*1000, color = TREATMENT_PHASE))+
  geom_point()+
  scale_color_manual(values = c("#f3ca40","#577590"))+
  labs(x = "hours",
       y = expression(bold("CO"[2]*" (" * mu *"g C g"^{-1}*"hr"^{-1}*")")))+
  
  facet_grid(Treatment~Site)+
  theme_kp()
#  scale_x_date(date_breaks = "14 days")

ggplot(flux, aes(x = time_hours, y = CH4_mgC_gSoil_hr*1e6, color = TREATMENT_PHASE))+
  geom_point()+
  scale_color_manual(values = c("#f3ca40","#577590"))+
  labs(x = "hours",
       y = expression(bold("CH"[4]*" (ng C g"^{-1}*"hr"^{-1}*")")))+
  facet_grid(Treatment~Site)+
  theme_kp()
```

```{r birch, fig.height=5, fig.width=5}
ggplot(flux[flux$Treatment=="drought",], 
       aes(x = Site, y = CO2_mgC_gSoil_hr*1000,
           fill = TREATMENT_PHASE))+
  
  geom_boxplot(width=0.5, alpha = 0.5)+
  #scale_color_manual(values = c("grey40","darkblue"))+
  scale_fill_manual(values = c("#f3ca40","#577590"))+
  labs(x = "",
       y = expression(bold("CO"[2]*" (" * mu *"g C g"^{-1}*"hr"^{-1}*")")))+

  annotate("text", label = "*", x = 1, y = 40, size=7)+
  annotate("text", label = "*", x = 2, y = 2, size=7)+
  annotate("text", label = "*", x = 3, y = 50, size=7)+
  theme_kp()+ theme(legend.position = c(0.3, 0.8))

```


```{r normalized_C, include=FALSE}
flux = 
  flux %>% 
  dplyr::mutate(
    TC = case_when(
      Site=="CPCRW" ~ 1.43,
      Site=="DWP" ~ 0.98,
      Site=="SR" ~ 10.32),
    CO2_mgC_gC_hr = CO2_mgC_gSoil_hr*100/TC
  ) 

ggplot(flux, aes(x = Site, y = CO2_mgC_gC_hr,
                 color = TREATMENT_PHASE))+
  geom_boxplot()+
  facet_grid(.~Treatment)
```

by core: CPCRW


```{r, include=FALSE, fig.width=8, fig.height=8}
## ggplot(flux[flux$Site=="CPCRW",], aes(x = as.Date(DATETIME), y = CO2_mgC_gSoil_hr, color = TREATMENT_PHASE))+
##   geom_point()+
##   facet_wrap(Treatment~SampleID, scales = "free_x")+
##   scale_x_date(date_breaks = "7 days")
## 
## ggplot(flux[flux$Site=="CPCRW",], aes(x = as.Date(DATETIME), y = CH4_mgC_gSoil_hr*1000000, color = ## TREATMENT_PHASE))+
##   geom_point()+
##   facet_wrap(Treatment~SampleID, scales = "free_x")+
##   scale_x_date(date_breaks = "7 days")
```

by core: DWP
```{r, include=FALSE, fig.width=8, fig.height=8}
## ggplot(flux[flux$Site=="DWP",], aes(x = as.Date(DATETIME), y = CO2_mgC_gSoil_hr, color = TREATMENT_PHASE))+
##   geom_point()+
##   facet_wrap(Treatment~SampleID, scales = "free_x")+
##   scale_x_date(date_breaks = "7 days")
## 
## ggplot(flux[flux$Site=="DWP",], aes(x = as.Date(DATETIME), y = CH4_mgC_gSoil_hr*1000000, color = ## TREATMENT_PHASE))+
##   geom_point()+
##   facet_wrap(Treatment~SampleID, scales = "free_x")+
##   scale_x_date(date_breaks = "7 days")
```

by core: SR

```{r, include=FALSE, fig.width=8, fig.height=8}
## ggplot(flux[flux$Site=="SR",], aes(x = as.Date(DATETIME), y = CO2_mgC_gSoil_hr, color = TREATMENT_PHASE))+
##   geom_point()+
##   facet_wrap(Treatment~SampleID, scales = "free_x")+
##   scale_x_date(date_breaks = "7 days")
## 
## ggplot(flux[flux$Site=="SR",], aes(x = as.Date(DATETIME), y = CH4_mgC_gSoil_hr*1000000, color = TREATMENT_PHASE))+
##   geom_point()+
##   facet_wrap(Treatment~SampleID, scales = "free_x")+
##   scale_x_date(date_breaks = "7 days")
```

graphs

```{r, include=FALSE}
## flux2 = 
##   flux %>% 
##   na.omit() %>% 
##   filter(!SampleID=="S5") %>% 
##   dplyr::mutate(CO2_mgC_gSoil_hr = if_else(CO2_mgC_gSoil_hr>0,CO2_mgC_gSoil_hr, as.numeric(NA)),
##                 CH4_mgC_gSoil_hr = if_else(CH4_mgC_gSoil_hr>0,CH4_mgC_gSoil_hr, as.numeric(NA))) %>%
##   group_by(Site, Treatment)%>% 
##   dplyr::mutate(DATE = as.Date(DATETIME),
##                 time_days = as.numeric(difftime(DATE, min(DATE), units = "days")),
##                 time_hours = round(time_hours,2))
## flux_mean = 
##   flux2 %>% 
##   dplyr::mutate(time_hours = time_days*24) %>% 
##   group_by(Site, TREATMENT_PHASE, time_hours, Treatment) %>% 
##   dplyr::summarise(CO2 = mean(CO2_mgC_gSoil_hr, na.omit = TRUE),
##                    CH4 = mean(CH4_mgC_gSoil_hr, na.omit = TRUE))
## 
## ggplot(flux_mean[!flux_mean$Treatment=="sat_I",], aes(x = time_hours, y = CO2, color = TREATMENT_PHASE))+
##   geom_smooth(data=flux2[!flux2$Treatment=="sat_I",],aes( y = CO2_mgC_gSoil_hr, group = SampleID), se = FALSE, ## color = "grey",alpha = 0.5, size=0.5)+
##   geom_point(data=flux2[!flux2$Treatment=="sat_I",],aes( y = CO2_mgC_gSoil_hr, group = SampleID), color = ## "grey",alpha = 0.5, size=1)+
##   geom_point(size=3)+
##   #geom_smooth(method = "loess",color = "red")+
##   facet_grid(Site~Treatment)+
##   ylab("CO2, mgC/g/hr")+
##   theme_kp()+theme(legend.position = "none")
## 
## ggplot(flux_mean[!flux_mean$Treatment=="sat_I",], aes(x = time_hours, y = CH4*1e6, color = TREATMENT_PHASE))+
##   geom_smooth(data=flux[!flux$Treatment=="sat_I",],aes( y = CH4_mgC_gSoil_hr*1e6, group = SampleID), se = FALSE, ## color = "grey",alpha = 0.7)+
##   geom_point(data=flux[!flux$Treatment=="sat_I",],aes( y = CH4_mgC_gSoil_hr*1e6, group = SampleID), color = ## "grey",alpha = 0.5, size=1)+
##   geom_point(size=2)+
##   #geom_smooth(method = "loess",color = "red")+
##   facet_grid(Site~Treatment)+
##   ylab("CH4, ngC/g/hr")+
##   theme_kp()+theme(legend.position = "none")


```

